# Generated by Django 3.1.7 on 2021-03-30 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0012_auto_20210330_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(db_column='DATE', default=datetime.datetime(2021, 3, 30, 22, 53, 17, 648870), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(db_column='DATE', default=datetime.datetime(2021, 3, 30, 22, 53, 17, 649873), primary_key=True, serialize=False),
        ),
    ]
