# Generated by Django 3.1.7 on 2021-03-30 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0013_auto_20210330_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(db_column='Image', null=True, upload_to='cd/C:/Users/Hariprasad/RAS/ras_frontend/src/components/images/'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(db_column='DATE', default=datetime.datetime(2021, 3, 30, 22, 54, 17, 419330), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(db_column='DATE', default=datetime.datetime(2021, 3, 30, 22, 54, 17, 419330), primary_key=True, serialize=False),
        ),
    ]
