# Generated by Django 3.1.7 on 2021-04-06 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0024_auto_20210405_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyconsumption',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 6)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(db_column='DATE', default=datetime.datetime(2021, 4, 6, 16, 20, 48, 584810), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(db_column='DATE', default=datetime.datetime(2021, 4, 6, 16, 20, 48, 584810), null=True),
        ),
    ]
