# Generated by Django 3.1.7 on 2021-04-07 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0025_auto_20210406_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=50)),
                ('amount', models.FloatField(null=True)),
                ('is_ordered', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'PurchaseList',
                'db_table': 'PurchaseList',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 7)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(db_column='DATE', default=datetime.datetime(2021, 4, 7, 17, 18, 44, 807107)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(db_column='DATE', default=datetime.datetime(2021, 4, 7, 17, 18, 44, 807107), null=True),
        ),
    ]
